CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Controllers/AdminMovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CinemaTicketsBookingSystem.Data;
using CinemaTicketsBookingSystem.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace CinemaTicketsBookingSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminMovieController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment; // needed for posting images in the wwwroot

        public AdminMovieController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: AdminMovie
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Movies.Include(m => m.Genre);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: AdminMovie/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: AdminMovie/Create
        public IActionResult Create()
        {
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name");
            return View();
        }

        // POST: AdminMovie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseYear,Duration,GenreId,Plot,Director,PosterUrl")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(webRootPath, @"img\posters");
                var extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                movie.PosterUrl = @"img\posters\" + fileName + extension;

                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", movie.GenreId);
            return View(movie);
        }

        // GET: AdminMovie/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", movie.GenreId);
            return View(movie);
        }

        // POST: AdminMovie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseYear,Duration,GenreId,Plot,Director,PosterUrl")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(_context.Genres, "Id", "Name", movie.GenreId);
            return View(movie);
        }

        // GET: AdminMovie/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: AdminMovie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CinemaTicketsBookingSystem.Data;
using CinemaTicketsBookingSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaTicketsBookingSystem.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MoviesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var movies = _db.Movies
                .Include(m => m.Genre);

            return View(await movies.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var movie = await _db.Movies
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (movie == null) return NotFound();            

            return View(movie);
        }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Controllers/ShowtimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CinemaTicketsBookingSystem.Data;
using CinemaTicketsBookingSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaTicketsBookingSystem.Controllers
{
    public class ShowtimesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ShowtimesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(int? id, string sortby)
        {
            if (!_db.Showtimes.Any(s => s.Time.Date == DateTime.Today))
            {
                var movies = _db.Movies.OrderBy(m => Guid.NewGuid()).Take(6);

                var cinemaHalls = _db.CinemaHalls.ToList();
                int time = 15;
                int count = 1;
                decimal price;

                foreach (var movie in movies)
                {
                    var cinemaHall = (count <= 3) ? cinemaHalls[0] : cinemaHalls[1];
                    price = (time == 15) ? 49 : (time == 18) ? 69 : 89;
                    _db.Showtimes.Add(new Showtime
                    {
                        Time = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, time, 0, 0),
                        MovieId = movie.Id,
                        CinemaHallId = cinemaHall.Id,
                        TicketPrice = price,
                        TicketsAvailable = cinemaHall.SeatingCapacity
                    });
                    count++;
                    time = (time == 21) ? 15 : time += 3;
                }
            }
            _db.SaveChanges();

            var showtimes = await _db.Showtimes
                .Include(s => s.Movie)
                .Include(s => s.CinemaHall)
                .Where(s => s.Time.Day == DateTime.Now.Day)
                .ToListAsync();

            switch (sortby)
            {
                case "priceAsc":
                    showtimes = showtimes.OrderBy(s => s.TicketPrice).ToList();
                    break;
                case "priceDesc":
                    showtimes = showtimes.OrderByDescending(s => s.TicketPrice).ToList();
                    break;
                case "startingTimeAsc":
                    showtimes = showtimes.OrderBy(s => s.Time).ToList();
                    break;
                case "startingTimeDesc":
                    showtimes = showtimes.OrderByDescending(s => s.Time).ToList();
                    break;
                case "ticketsLeftAsc":
                    showtimes = showtimes.OrderBy(s => s.TicketsAvailable).ToList();
                    break;
                case "ticketsLeftDesc":
                    showtimes = showtimes.OrderByDescending(s => s.TicketsAvailable).ToList();
                    break;
                case "durationAsc":
                    showtimes = showtimes.OrderBy(s => s.Movie.Duration).ToList();
                    break;
                case "durationDesc":
                    showtimes = showtimes.OrderByDescending(s => s.Movie.Duration).ToList();
                    break;
                default:
                    break;
            }


            if (id != null)
            {
                showtimes = showtimes.Where(s => s.Movie.Id == id).ToList();
            }

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                var count = _db.ShoppingCarts.Where(s => s.ApplicationUserId == claim.Value)
                    .ToList()
                    .Count();

                HttpContext.Session.SetInt32("Shopping cart session", count);
            }

            return View(showtimes);
        }

        public async Task<IActionResult> Buy(int? id)
        {
            if (id == null) return NotFound();

            var showtime = await _db.Showtimes
                .Include(s => s.Movie)
                .Include(s => s.CinemaHall)
                .FirstOrDefaultAsync(s => s.Id == id);

            if (showtime == null) return NotFound();

            ShoppingCart shoppingCart = new ShoppingCart()
            {
                Item = showtime,
                ItemId = showtime.Id
            };

            return View(shoppingCart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Buy(ShoppingCart cartItem)
        {
            cartItem.Id = 0;

            if (ModelState.IsValid)
            {
                // ad to cart
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                cartItem.ApplicationUserId = claim.Value;

                ShoppingCart cartFromDb = _db.ShoppingCarts
                    .Include(s => s.Item)
                    .FirstOrDefault(s => s.ApplicationUserId == cartItem.ApplicationUserId && s.ItemId == cartItem.ItemId);

                if (cartFromDb == null)
                {
                    // No record for this user and this showtime item, create a new one
                    _db.ShoppingCarts.Add(cartItem);
                }
                else
                {
                    // Increase count of the existing showtime item
                    if (cartFromDb.Count + cartItem.Count <= 12)
                    {
                        cartFromDb.Count += cartItem.Count;
                        _db.ShoppingCarts.Update(cartFromDb);
                    }                    
                }
                _db.SaveChanges();

                var count = _db.ShoppingCarts
                    .Where(s => s.ApplicationUserId == cartItem.ApplicationUserId)
                    .ToList()
                    .Count();

                HttpContext.Session.SetInt32("Shopping cart session", count);

                return RedirectToAction(nameof(Index));
            }
            else if (cartItem.Count > 0)
            {
                var itemFromDb = _db.Showtimes
                    .Include(s => s.Movie)
                    .Include(s => s.CinemaHall)
                    .FirstOrDefault(s => s.Id == cartItem.ItemId);

                ShoppingCart shoppingCart = new ShoppingCart()
                {
                    Item = itemFromDb,
                    ItemId = itemFromDb.Id
                };

                return View(cartItem);
            }
            else
            {
                return View();
            }
        }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Berras Bio - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-dark bg-primary box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Berras Bio</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Movies" asp-action="Index">Entire Repertoire</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Showtimes" asp-action="Index" asp-route-id="@null">What's On Today</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-danger" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin Zone</a>
                                <div class="dropdown-menu bg-primary" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminMovie" asp-action="Index">Movies</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="AdminPurchases" asp-action="Index">Purchases</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container" style="width: 100vw;">
            &copy; 2020 - Ticket Booking System - by <a href="https://github.com/HubTicaBB" class="text-primary">Tica BB</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>