CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Models/ShoppingCart.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaTicketsBookingSystem.Models
{
    public class ShoppingCart
    {
        public ShoppingCart()
        {
            Count = 1;
        }

        public int Id { get; set; }

        public string ApplicationUserId { get; set; }
        [ForeignKey("ApplicationUserId")]
        public IdentityUser ApplicationUser { get; set; }

        public int ItemId { get; set; }
        [ForeignKey("ItemId")]
        public Showtime Item { get; set; }

        [Range(1, 12, ErrorMessage = "Number of tickets per purchase: min 1 - max 12")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Please enter a valid number. The minimum number of tickets is 1.")]        
        public int Count { get; set; }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Models/ShoppingCartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaTicketsBookingSystem.Models
{
    public class ShoppingCartViewModel
    {
        public IEnumerable<ShoppingCart> ShoppingCarts { get; set; }
        public PurchaseHeader PurchaseHeader { get; set; }
        public Payment Payment { get; set; }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CinemaTicketsBookingSystem.Data;
using CinemaTicketsBookingSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaTicketsBookingSystem.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MoviesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var movies = _db.Movies
                .Include(m => m.Genre);

            return View(await movies.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var movie = await _db.Movies
                .Include(m => m.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (movie == null) return NotFound();            

            return View(movie);
        }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Controllers/ShoppingCartsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CinemaTicketsBookingSystem.Data;
using CinemaTicketsBookingSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.Win32.SafeHandles;

namespace CinemaTicketsBookingSystem.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public ShoppingCartViewModel ShoppingCartVM { get; set; }

        public ShoppingCartsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartViewModel()
            {
                PurchaseHeader = new PurchaseHeader(),
                ShoppingCarts = await _db.ShoppingCarts
                    .Include(s => s.Item)
                    .Include(s => s.Item.Movie)
                    .Include(s => s.Item.CinemaHall)
                    .Where(s => s.ApplicationUserId == claim.Value)
                    .ToListAsync()
            };

            ShoppingCartVM.PurchaseHeader.TotalAmount = 0;
            ShoppingCartVM.PurchaseHeader.ApplicationUser = _db.Users.FirstOrDefault(u => u.Id == claim.Value);

            foreach (var item in ShoppingCartVM.ShoppingCarts)
            {
                ShoppingCartVM.PurchaseHeader.TotalAmount += (item.Item.TicketPrice * item.Count);
            }

            return View(ShoppingCartVM);
        }

        public IActionResult Plus(int? cartid)
        {
            if (cartid == null) return NotFound();

            var shoppingCart = _db.ShoppingCarts.FirstOrDefault(s => s.Id == cartid);
            if (shoppingCart == null) return NotFound();

            var showtimeFromDb = _db.Showtimes.FirstOrDefault(s => s.Id == shoppingCart.ItemId);
            if (showtimeFromDb == null) return NotFound();

            if (shoppingCart.Count < 12 && shoppingCart.Count < showtimeFromDb.TicketsAvailable)
            {
                shoppingCart.Count += 1;
            }

            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Minus(int? cartid)
        {
            if (cartid == null) return NotFound();

            var shoppingCart = _db.ShoppingCarts.FirstOrDefault(s => s.Id == cartid);

            if (shoppingCart == null) return NotFound();

            if (shoppingCart.Count == 1)
            {
                var countFromDb = _db.ShoppingCarts.Where(s => s.ApplicationUserId == shoppingCart.ApplicationUserId).ToList().Count();
                _db.ShoppingCarts.Remove(shoppingCart);
                _db.SaveChanges();
                HttpContext.Session.SetInt32("Shopping cart session", countFromDb - 1);
            }
            else
            {
                shoppingCart.Count -= 1;
                _db.SaveChanges();
            }

            if (shoppingCart == null) return NotFound();

            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int? cartId)
        {
            var shoppingCart = _db.ShoppingCarts.FirstOrDefault(s => s.Id == cartId);
            var countFromDb = _db.ShoppingCarts.Where(s => s.ApplicationUserId == shoppingCart.ApplicationUserId).ToList().Count();

            _db.ShoppingCarts.Remove(shoppingCart);
            _db.SaveChanges();

            HttpContext.Session.SetInt32("Shopping cart session", countFromDb - 1);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Checkout()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartViewModel()
            {
                PurchaseHeader = new PurchaseHeader(),
                ShoppingCarts = await _db.ShoppingCarts
                    .Include(s => s.Item)
                    .Include(s => s.Item.Movie)
                    .Include(s => s.Item.CinemaHall)
                    .Where(s => s.ApplicationUserId == claim.Value)
                    .ToListAsync()
            };

            ShoppingCartVM.PurchaseHeader.ApplicationUser = _db.Users.FirstOrDefault(u => u.Id == claim.Value);

            foreach (var item in ShoppingCartVM.ShoppingCarts)
            {
                ShoppingCartVM.PurchaseHeader.TotalAmount += (item.Item.TicketPrice * item.Count);
            }

            return View(ShoppingCartVM);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Checkout")]
        public IActionResult CheckoutPost()
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("PurchaseConfirmation");
            }
            else
            {
                return View();
            }
        }

        public IActionResult PurchaseConfirmation()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartViewModel()
            {
                PurchaseHeader = new PurchaseHeader(),
                ShoppingCarts = _db.ShoppingCarts
                    .Include(s => s.Item)
                    .Include(s => s.Item.Movie)
                    .Include(s => s.Item.CinemaHall)
                    .Where(s => s.ApplicationUserId == claim.Value)
                    .ToList()
            };

            ShoppingCartVM.PurchaseHeader.ApplicationUser = _db.Users.FirstOrDefault(u => u.Id == claim.Value);
            ShoppingCartVM.PurchaseHeader.UserName = ShoppingCartVM.PurchaseHeader.ApplicationUser.UserName;
            ShoppingCartVM.PurchaseHeader.Status = "Completed";
            ShoppingCartVM.PurchaseHeader.PaymentStatus = "Completed";
            ShoppingCartVM.PurchaseHeader.ApplicationUserId = claim.Value;
            ShoppingCartVM.PurchaseHeader.Date = DateTime.Now;

            _db.PurchaseHeaders.Add(ShoppingCartVM.PurchaseHeader);
            _db.SaveChanges();

            foreach (var item in ShoppingCartVM.ShoppingCarts)
            {
                PurchaseDetails purchaseDetails = new PurchaseDetails()
                {
                    ItemId = item.Item.Id,
                    PurchaseId = ShoppingCartVM.PurchaseHeader.Id,
                    Price = item.Item.TicketPrice,
                    Count = item.Count
                };
                ShoppingCartVM.PurchaseHeader.TotalAmount += purchaseDetails.Count * purchaseDetails.Price;
                _db.PurchaseDetails.Add(purchaseDetails);

                var itemFromDb = _db.Showtimes.FirstOrDefault(s => s.Id == item.Item.Id);
                itemFromDb.TicketsAvailable -= item.Count;
                _db.Showtimes.Update(itemFromDb);
            }
            _db.SaveChanges();

            var allTickets = _db.PurchaseDetails.Where(p => p.PurchaseId == ShoppingCartVM.PurchaseHeader.Id).ToList();

            _db.ShoppingCarts.RemoveRange(ShoppingCartVM.ShoppingCarts);
            _db.SaveChanges();
            HttpContext.Session.SetInt32("Shopping cart session", 0);

            return View(allTickets);
        }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Controllers/ShowtimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CinemaTicketsBookingSystem.Data;
using CinemaTicketsBookingSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaTicketsBookingSystem.Controllers
{
    public class ShowtimesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ShowtimesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(int? id, string sortby)
        {
            if (!_db.Showtimes.Any(s => s.Time.Date == DateTime.Today))
            {
                var movies = _db.Movies.OrderBy(m => Guid.NewGuid()).Take(6);

                var cinemaHalls = _db.CinemaHalls.ToList();
                int time = 15;
                int count = 1;
                decimal price;

                foreach (var movie in movies)
                {
                    var cinemaHall = (count <= 3) ? cinemaHalls[0] : cinemaHalls[1];
                    price = (time == 15) ? 49 : (time == 18) ? 69 : 89;
                    _db.Showtimes.Add(new Showtime
                    {
                        Time = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, time, 0, 0),
                        MovieId = movie.Id,
                        CinemaHallId = cinemaHall.Id,
                        TicketPrice = price,
                        TicketsAvailable = cinemaHall.SeatingCapacity
                    });
                    count++;
                    time = (time == 21) ? 15 : time += 3;
                }
            }
            _db.SaveChanges();

            var showtimes = await _db.Showtimes
                .Include(s => s.Movie)
                .Include(s => s.CinemaHall)
                .Where(s => s.Time.Day == DateTime.Now.Day)
                .ToListAsync();

            switch (sortby)
            {
                case "priceAsc":
                    showtimes = showtimes.OrderBy(s => s.TicketPrice).ToList();
                    break;
                case "priceDesc":
                    showtimes = showtimes.OrderByDescending(s => s.TicketPrice).ToList();
                    break;
                case "startingTimeAsc":
                    showtimes = showtimes.OrderBy(s => s.Time).ToList();
                    break;
                case "startingTimeDesc":
                    showtimes = showtimes.OrderByDescending(s => s.Time).ToList();
                    break;
                case "ticketsLeftAsc":
                    showtimes = showtimes.OrderBy(s => s.TicketsAvailable).ToList();
                    break;
                case "ticketsLeftDesc":
                    showtimes = showtimes.OrderByDescending(s => s.TicketsAvailable).ToList();
                    break;
                case "durationAsc":
                    showtimes = showtimes.OrderBy(s => s.Movie.Duration).ToList();
                    break;
                case "durationDesc":
                    showtimes = showtimes.OrderByDescending(s => s.Movie.Duration).ToList();
                    break;
                default:
                    break;
            }


            if (id != null)
            {
                showtimes = showtimes.Where(s => s.Movie.Id == id).ToList();
            }

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                var count = _db.ShoppingCarts.Where(s => s.ApplicationUserId == claim.Value)
                    .ToList()
                    .Count();

                HttpContext.Session.SetInt32("Shopping cart session", count);
            }

            return View(showtimes);
        }

        public async Task<IActionResult> Buy(int? id)
        {
            if (id == null) return NotFound();

            var showtime = await _db.Showtimes
                .Include(s => s.Movie)
                .Include(s => s.CinemaHall)
                .FirstOrDefaultAsync(s => s.Id == id);

            if (showtime == null) return NotFound();

            ShoppingCart shoppingCart = new ShoppingCart()
            {
                Item = showtime,
                ItemId = showtime.Id
            };

            return View(shoppingCart);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Buy(ShoppingCart cartItem)
        {
            cartItem.Id = 0;

            if (ModelState.IsValid)
            {
                // ad to cart
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                cartItem.ApplicationUserId = claim.Value;

                ShoppingCart cartFromDb = _db.ShoppingCarts
                    .Include(s => s.Item)
                    .FirstOrDefault(s => s.ApplicationUserId == cartItem.ApplicationUserId && s.ItemId == cartItem.ItemId);

                if (cartFromDb == null)
                {
                    // No record for this user and this showtime item, create a new one
                    _db.ShoppingCarts.Add(cartItem);
                }
                else
                {
                    // Increase count of the existing showtime item
                    if (cartFromDb.Count + cartItem.Count <= 12)
                    {
                        cartFromDb.Count += cartItem.Count;
                        _db.ShoppingCarts.Update(cartFromDb);
                    }                    
                }
                _db.SaveChanges();

                var count = _db.ShoppingCarts
                    .Where(s => s.ApplicationUserId == cartItem.ApplicationUserId)
                    .ToList()
                    .Count();

                HttpContext.Session.SetInt32("Shopping cart session", count);

                return RedirectToAction(nameof(Index));
            }
            else if (cartItem.Count > 0)
            {
                var itemFromDb = _db.Showtimes
                    .Include(s => s.Movie)
                    .Include(s => s.CinemaHall)
                    .FirstOrDefault(s => s.Id == cartItem.ItemId);

                ShoppingCart shoppingCart = new ShoppingCart()
                {
                    Item = itemFromDb,
                    ItemId = itemFromDb.Id
                };

                return View(cartItem);
            }
            else
            {
                return View();
            }
        }
    }
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Views/ShoppingCarts/Checkout.cshtml
@model CinemaTicketsBookingSystem.Models.ShoppingCartViewModel

@{
    ViewData["Title"] = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-controller="ShoppingCarts" asp-action="Checkout" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <br />
    <div class="card-header bg-dark text-light row">
        <div class="col-6">
            <h5><i class="far fa-credit-card"></i>&nbsp; Checkout</h5>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ShoppingCarts" asp-action="Index" class="btn btn-outline-info">Back to <i class="fa fa-shopping-cart"></i></a>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-lg-6 pb-4 pl-0 pr-0">
                <h5 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-info">Your Shopping Cart:</span>
                </h5>
                <ul class="list-group mb-3">
                    @foreach (var item in Model.ShoppingCarts)
                    {
                        <li class="list-group-item d-flex justify-content-between">
                            <div>
                                <h6 class="my-0">@item.Item.Movie.Title</h6>
                                <small class="text-muted">Quantity: @item.Count</small>
                            </div>
                            @{ var totalPerItem = item.Item.TicketPrice * item.Count; }
                            <span class="text-muted">@totalPerItem.ToString("C") </span>
                        </li>
                    }
                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <span class="text-info">Total</span>
                        <strong class="text-info">@(Model.PurchaseHeader.TotalAmount.ToString("C"))</strong>
                    </li>
                </ul>
            </div>
            <div class="col-12 col-lg-5 offset-lg-1 pl-0 pr-0">
                <h5 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-info">Enter Your Payment Details:</span>
                </h5>
                <div class="form-group">
                    <label asp-for="@Model.Payment.NameOnCard" class="control-label"></label>
                    <input asp-for="@Model.Payment.NameOnCard" class="form-control" />
                    <span asp-validation-for="@Model.Payment.NameOnCard" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Payment.CardNumber" class="control-label"></label>
                    <input asp-for="@Model.Payment.CardNumber" class="form-control" />
                    <span asp-validation-for="@Model.Payment.CardNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Payment.ExpirationDate" class="control-label"></label>
                    <select asp-for="@Model.Payment.ExpirationDate" class="form-control">
                        @{
                            var year = DateTime.Now.Year;
                        }
                        @for (int y = year; y <= 2022; y++)
                        {
                            var month = (y == year) ? DateTime.Now.Month : 1;
                            for (int m = month; m <= 12; m++)
                            {
                                <option>@m / @y</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="@Model.Payment.ExpirationDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Payment.CVV" class="control-label"></label>
                    <input asp-for="@Model.Payment.CVV" class="form-control" />
                    <span asp-validation-for="@Model.Payment.CVV" class="text-danger"></span><br /><br />
                </div>
                <div class="form-group">
                    <label asp-for="@Model.PurchaseHeader.TotalAmount" class="control-label"></label><br />
                    <input asp-for="@Model.PurchaseHeader.TotalAmount" class="form-control bg-dark text-warning" disabled />
                </div>
                <hr />

                <button type="submit" class="btn btn-success form-control btn-lg" id="submit-btn">Submit</button>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Views/ShoppingCarts/Index.cshtml
@model CinemaTicketsBookingSystem.Models.ShoppingCartViewModel 

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}    

    <form method="post">
        <br />
        <div class="card-header bg-dark text-light row">
            <div class="col-6">
                <h5><i class="fa fa-shopping-cart"></i> &nbsp; <span class="h-resp">Your Shopping Cart</span></h5>
            </div>
            <div class="col-6 text-right">
                <a asp-controller="Showtimes" asp-action="Index" class="btn btn-outline-info">Continue Shopping</a>
            </div>
        </div>
        @if (Model.ShoppingCarts.Count() > 0)
        {
            <div class="card-body pl-0 pr-0">
                @foreach (var item in Model.ShoppingCarts)
                {
                    <div class="row">
                        <div class="d-none d-lg-block col-lg-1 text-center py-2">
                            <img src="@Url.Content(item.Item.Movie.PosterUrl)" class="rounded" width="100%" />
                        </div>
                        <div class="col-12 text-sm-center col-lg-6 text-lg-left">
                            <h5 class="text-light"><strong>@item.Item.Movie.Title</strong><span class="text-muted font-weight-light"> (@item.Item.Movie.ReleaseYear)</span></h5>
                            <p class="text-muted">by <span class="text-light">@item.Item.Movie.Director</span></p>
                            <p class="text-muted">Cinema Hall: <span class="text-light">@item.Item.CinemaHall.Name</span></p>
                            <p class="text-muted">Time: <span class="text-light">@item.Item.Time.ToString("HH:mm")</span></p>
                        </div>
                        <div class="col-12 text-sm-left col-lg-5 text-lg-left row">
                            <div class="col-6 col-sm-6 text-md-left" style="padding-top:5px;">
                                <h6><strong class="text-light">@item.Item.TicketPrice.ToString("C")<span class="text-muted"> x </span>@item.Count</strong></h6>
                                @if (@item.Count == 12)
                                {
                                    <p class="text-danger text-sm-left">Note: 12 is max</p>
                                }
                            </div>
                            <div class="col-4 col-sm-4 pl-0 pr-0">
                                <div class="float-right mx-1">
                                    <a asp-action="Plus" asp-route-cartId="@item.Id" class="btn btn-outline-info" title="Note: Max 12 tickets per showtime">
                                        <i class="fas fa-plus"></i>
                                    </a>
                                </div>
                                <div class="float-right mx-1">
                                    <a asp-action="Minus" asp-route-cartId="@item.Id" class="btn btn-outline-warning" title="Note: Min 1 ticket per showtime">
                                        <i class="fas fa-minus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="col-2 col-lg-2 text-right">
                                <a asp-action="Remove" asp-route-cartId="@item.Id" class="btn btn-outline-danger">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <hr />
                }
                <div class="row">
                    <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                        <div class="bg-dark list-group-item d-flex justify-content-between">
                            <span class="text-info">Total</span>
                            <strong class="text-info">$ <span id="txtOrderTotal">@Model.PurchaseHeader.TotalAmount.ToString("C")</span></strong>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                        <a asp-controller="ShoppingCarts" asp-action="Checkout" class="btn btn-outline-success btn-square btn-lg form-control">Proceed to Checkout</a>
                    </div>
                </div>
            </div>
        }
        else
        {
            <p class="text-light p-4">Your Shopping Cart is empty</p>
        }
    </form>

CinemaTicketsBookingSystem/CinemaTicketsBookingSystem/Views/ShoppingCarts/PurchaseConfirmation.cshtml
@model IEnumerable<CinemaTicketsBookingSystem.Models.PurchaseDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <br />
    <div class="card-header bg-dark text-light row pl-0 pr-0">
        <div class="col-12">
            <h4 class="text-success"><i class="far fa-check-circle"></i> &nbsp; You have successfully completed your purchase</h4>
            <a asp-controller="Movies" asp-action="Index" class="btn btn-outline-info float-right">Back to movie repertoire</a>
            <h5 class="text-muted">Your tickets:</h5>
        </div>
    </div>
    <div class="card-body pl-0 pr-0">

        @foreach (var ticket in Model)
        {
            for (int i = 0; i < ticket.Count; i++)
            {
                <div class="card text-white border-light mb-3">
                    <div class="card-header col-lg-auto justify-content-between">
                        <span class="navbar-brand">Berras Bio</span>
                        @{ var barcode = "https://api.qrserver.com/v1/create-qr-code/?size=100x100&data=" + ticket.PurchaseId + ticket.Item.Id + i; }
                        <img class="float-right" src=@barcode /><br />
                        <i class="fas fa-ticket-alt fa-2x"></i>&nbsp; Ticket No. @ticket.Id-@i
                    </div>
                    <div class="card-body">
                        <h3 class="card-title">@ticket.Item.Movie.Title (@ticket.Item.Movie.ReleaseYear)</h3>
                        <h6 class="card-subtitle mb-2">by @ticket.Item.Movie.Director</h6>
                        <hr />
                        <div class="ml-0">
                            <div class="card-text row col-lg-auto justify-content-between ml-0 mr-0 pl-0 pr-0">
                                <div class="col-6 text-uppercase pl-0 pr-0">Cinema Hall: </div>
                                <div class="col-6">@ticket.Item.CinemaHall.Name</div>
                            </div>
                            <div class="card-text row col-lg-auto justify-content-between ml-0 mr-0 pl-0 pr-0">
                                <div class="col-6 text-uppercase pl-0 pr-0">Date: </div>
                                <div class="col-6">@DateTime.Today.Date.ToLongDateString()</div>
                            </div>
                            <div class="card-text row col-lg-auto justify-content-between ml-0 mr-0 pl-0 pr-0">
                                <div class="col-6 text-uppercase pl-0 pr-0">Time: </div>
                                <div class="col-6">@ticket.Item.Time.ToString("HH:mm")</div>
                            </div>
                            <div class="card-text row col-lg-auto justify-content-between ml-0 mr-0 pl-0 pr-0">
                                <div class="col-6 text-uppercase pl-0 pr-0">Price: </div>
                                <div class="col-6">@ticket.Item.TicketPrice.ToString("C")</div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>